server:
  port: 8888
  
spring:
  application:
    name: CONFIG-SERVER
    
  # active profile
#  profiles:
#     active: native

  cloud:
    config:
     server:
       git:
         default-label: main
         uri: https://github.com/LiamJDesmond84/Photo-App-Spring-Cloud-Config-Repo
         #clone-on-start: true
         
       ## native application config location(local) if you want configs to come from here instead of GitHub(choose in spring.profiles.active)
       ## /// for Windows(I think), don't need to provide file name, just the folder it's in.  It will be an application.yml/properties file(Just like the default or GitHub Config Repo files)
#       native:
#          search-locations: file:///${user.home}/Desktop/ConfigsPlace/
          ## To test run this Config-Server then with Postman: GET http://8888/CONFIG-SERVER/native.  It should return your native application file configs.
         
  rabbitmq:
     host: localhost
#     port: 15672
     port: 5672
     username: guest
     password: guest

# For actuator refresh posts
management:
   endpoints:
      web:
         exposure:
            include: busrefresh
         

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    instance:
#      hostname: localhost